export const competences: string[] = [
  "React.js",
  "React Native",
  "Javascript",
  "Node.js",
  "Symfony4",
  "HTML5",
  "CSS",
  "Django",
  "Bootstrap",
  "Firebase",
  "Express",
  "Linux",
  "MongoDB",
  "Machine Learning",
  "Deep Learning",
  "Contentful",
  "REST",
  "Angular",
  "NestJS",
  "Vue.js",
  "Python",
  "SmartContract",
  "NFT",
  "C++",
  "Flutter",
  "Docker",
  "Kubernetes",
  "Ionic",
  "Dart",
  "Flask",
  "FastAPI",
  "SOLID",
  "Architecture hexagonale",
  "Clean architecture",
  "Test Driven Development (TDD)",
  "GraphQL",
  "SQL",
  "Loopback",
  "Meteor.JS",
  "Scrum",
  "GitHub",
  "Ruby",
  "SemanticUI",
  "Redux",
  "UX/UI",
  "Git",
  "Firebase",
  "Amazon Web Service",
  "Microsoft Azure",
  "Cybersécurité",
  "Gestion incident cybersécurité",
  "Intelligence Artificielle",
  "Sécurité informatique",
  "Développement de service Back End",
  "Développement d’interface Front End",
  "Automatisation des scripts",
  "WebScraping",
  "Cloud et infrastructure",
  "Data management",
  "Gestion du changement",
  "DevOps",
  "Création de sites internet",
  "SEO",
  "SEA",
  "UX/UI",
  "Webdesign",
  "Branding",
  "Responsive design",
  "Graphisme",
  "Sketch",
  "Identité visuelle",
  "Charte graphique",
  "Design logo",
  "Direction artistique",
  "Site vitrine",
  "User Testing",
  "Wireframing",
  "CSS3",
  "Mobile first",
  "Design Thinking",
  "Design produit",
  "Web3",
  "AdobeXD",
  "Design System",
  "Prototype",
  "Webflow",
  "Figma",
  "Suite Adobe",
  "Utilisation de logiciels de retouches/ création contenus",
  "Photoshop",
  "GIMP",
  "Lightroom",
  "Photofiltre",
  "Rawtherapee",
  "Illustrator",
  "Canva",
  "Adobe Express",
  "Indesign",
  "Montage vidéo",
  "DaVinci Resolve",
  "VideoPage",
  "Openshot",
  "Blender",
  "Avidemux",
  "Kendlive",
  "Vimeo Create",
  "Adobe Premiere Pro",
  "InVideo",
  "Movie Maker 10",
  "Wevideo",
  "Capcut",
  "Lightworks",
  "Shotcut",
  "iMovie",
  "HitFilm Express",
  "VSDC Free Video Editor",
  "Communication digitale",
  "Brand content",
  "Relations presse",
  "Social media manager",
  "Stratégie webmarketing",
  "Rédaction",
  "Marketing de contenu",
  "Réseaux sociaux",
  "Facebook",
  "Instagram",
  "Linkedin",
  "MetaBusiness",
  "Emailing",
  "Brevo",
  "Mailchimp",
  "Hubspot",
  "Mailjet",
  "Aweber",
  "Active Trail",
  "Moosend",
  "Klaviyo",
  "MailerLite",
  "Omnisend",
  "Maîtrise des logiciels bureautiques",
  "Mise en page",
];
